#!/bin/sh
#
# MIT © Sindre Sorhus - sindresorhus.com

# git hook to run a command after `git pull` if a specified file was changed

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
	echo "$changed_files" | grep -E --quiet "$1|$2" && eval "$3"
}

check_run test1.txt test2.txt "echo OKKKKKKK"

